version: '3.8'

services:
  wedding-photo-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount the source code for hot-reloading in development
      - .:/app
      # Use an anonymous volume to hide the host's node_modules
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3